import { useState } from 'react';
import creditscore1 from '../../assets/sample/creditscore1.png';
import creditscore2 from '../../assets/sample/creditscore2.png';

const CreditScore = () => {

  const [activeIndex, setActiveIndex] = useState(null);

  const toggleAnswer = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  const faqs = [
    {
      question: 'How do you get a 900 credit score?',
      answer:
        '  Achieving a 900 credit score involves consistently paying bills on time, maintaining low credit utilization, having a long credit history, and managing diverse credit types responsibly.'
    },
    {
      question: 'Who calculates the credit score in India?',
      answer:
        ' Credit scores in India are calculated by credit bureaus such as TransUnion CIBIL, Experian India, Equifax India, and CRIF High Mark, using data from lenders.'
    },
    {
      question: 'Is checking credit scores on third-party websites safe?',
      answer:
        ' It can be safe if the website is reputable and uses secure connections. Always verify the authenticity before sharing personal information.'
    },
    {
      question: 'Why do lenders check the Credit Score?',
      answer:
        'Lenders check credit scores to evaluate your creditworthiness and decide whether to approve loans or credit and determine the interest rates.'
    },
    {
      question: 'What information is included in my credit report?',
      answer:
        'Your credit report contains details about your credit accounts, payment history, outstanding debts, credit inquiries, and public records like bankruptcies.'
    },
    {
      question: 'How long does the information remain on a credit report?',
      answer:
        ' Most credit information remains on your report for up to 7 years, although the duration can vary depending on the type of information and regulations.'
    },
    {
      question: 'Is it possible to delete information from the credit report?',
      answer:
        'You can dispute inaccurate or outdated information with credit bureaus, but legitimate negative data usually remains for a set period.'
    },
    {
      question: 'Can I build a credit report with no credit history?',
      answer:
        'Without any credit history, it is difficult to build a credit report. Using secured credit cards or becoming an authorized user can help start your credit history.'
    },
    {
      question: 'What is SBI CIBIL score?',
      answer:
        'SBI CIBIL score refers to the credit score provided by TransUnion CIBIL, used by SBI (State Bank of India) and other lenders to evaluate loan applications.'
    },
    {
      question: 'Will the credit score be affected for owning multiple credit cards?',
      answer:
        'Owning multiple credit cards can affect your score depending on how you manage them. Responsible usage and low credit utilization can help; misuse can hurt your score.'
    },
    {
      question: 'Who generates credit scores?',
      answer:
        'Credit scores are generated by credit bureaus based on your credit data collected from banks, financial institutions, and lenders.'
    },
  ]
  return (

    <div>
      <div className="bg-gradient-to-b from-blue-100 to-white py-16">
        <div className="container mx-auto px-6 grid md:grid-cols-2 gap-8 mt-[30px] items-center">
          {/* Left Content */}
          <div>
            <h1 className="text-4xl md:text-5xl font-bold text-gray-800 leading-tight mb-4">Credit Score</h1>
            <p className="text-gray-600 text-lg mb-6">
              Discover what impacts your credit score, why it matters, and how you can boost it to secure better loan approvals and financial freedom.
            </p>

          </div>
          {/* Right Image or SVG Illustration */}
          <div className="flex justify-center">
            <img
              src={creditscore1}
              alt="Loan illustration"
              className="max-w-full h-auto"
            />
          </div>
        </div>
      </div>


      {/* Breadcrumb */}
      <div className="bg-[#fbfbfb] pl-12 py-3">
        <nav className="text-gray-600 text-sm flex items-center space-x-2">
          <a href="/" className="hover:underline text-[#0282ba]">Home</a>
          <span className="text-gray-400">&gt;</span>
          <span>Credit Score</span>
        </nav>
      </div>

      <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-10 lg:py-12 space-y-8">
        <div className="bg-white rounded-lg shadow-md mt-10 p-6">
          <div className="grid md:grid-cols-2 gap-6">
            <div className='rounded-lg flex flex-col justify-center items-center text-center'>
              <img
                src={creditscore2}
                alt="Credit Meter"
              />
            </div>

            <div>
              <p className="text-lg font-semibold mb-2">
                Get your Credit Score Report
              </p>
              <p className="text-sm mb-4">
                5 Lac+ people have got their Credit Scores for{' '}
                <span className="text-red-500 font-bold">FREE!</span>
              </p>
              <form className="space-y-4">
                <div className="grid md:grid-cols-2 gap-4">
                  <input
                    type="text"
                    placeholder="Full Name *"
                    className="w-full border rounded px-4 py-2"
                  />
                  <input
                    type="text"
                    placeholder="DOB (DD/MM/YYYY) *"
                    className="w-full border rounded px-4 py-2"
                  />
                </div>
                <div className="grid md:grid-cols-2 gap-4">
                  <input
                    type="email"
                    placeholder="Email Address *"
                    className="w-full border rounded px-4 py-2"
                  />
                  <input
                    type="text"
                    placeholder="PAN Card *"
                    className="w-full border rounded px-4 py-2"
                  />
                </div>
                <input
                  type="tel"
                  placeholder="Mobile No. *"
                  className="w-full border rounded px-4 py-2"
                />
                <div className="flex items-start space-x-2 text-sm">
                  <input type="checkbox" className="mt-1" />
                  <label>
                    I agree to the{' '}
                    <button
                      type="button"
                      className="text-blue-600 underline bg-transparent border-none p-0 m-0 cursor-pointer"
                      aria-label="Terms and Conditions"
                      onClick={() => { /* TODO: handle terms click */ }}
                    >
                      Terms and Conditions
                    </button>{' '}
                    of TUCIBIL and hereby provide explicit consent to share my
                    Credit Information with Urban Money Private Limited.
                  </label>
                </div>
                <button
                  type="submit"
                  className="bg-[#0282ba] text-white px-6 py-2 rounded hover:bg-indigo-700"
                >
                  Check Credit Score →
                </button>
              </form>
            </div>
          </div>
        </div>
        {/* </div> */}

        <div>
          <h2 className="text-3xl font-bold mb-4 text-[#0283BB]">What Is a Credit Score?</h2>
          <p className="text-gray-600 mb-4">
            A <strong>credit score</strong> is a three-digit number that represents your creditworthiness,
            or how likely you are to repay borrowed money on time. It is based on your credit history,
            including how much debt you have, your payment history, the types of credit you use, and
            the length of your credit history.
          </p>
          <p className="text-gray-600 mb-4">
            Credit scores are used by lenders, landlords, and even some employers to assess financial
            responsibility. Scores typically range from <strong>300 to 850</strong>—the higher the score,
            the better your credit profile.
          </p>
          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-800">Key Factors That Affect Your Credit Score:</h3>
          <ul className="list-disc list-inside text-gray-600 space-y-2 ml-4">
            <li><strong>Payment History</strong> – Whether you pay bills on time.</li>
            <li><strong>Credit Utilization</strong> – The ratio of your credit card balances to limits.</li>
            <li><strong>Length of Credit History</strong> – How long your credit accounts have been active.</li>
            <li><strong>Types of Credit</strong> – A mix of credit cards, loans, etc.</li>
            <li><strong>New Credit</strong> – Recent credit inquiries and new accounts.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-4 text-[#0283BB]">
            Why Is a Good Credit Score Important?
          </h2>
          <p className="text-gray-600 mb-6">
            A good credit score is more than just a number—it’s a financial asset
            that can open doors and save you money in various aspects of life.
          </p>
          <ul className="space-y-2">
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">
                Better Loan and Credit Card Approval Chances
              </h3>
              <p className="text-gray-600">
                Lenders use credit scores to assess your risk. A high score increases
                your chances of getting approved for loans and credit cards.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Lower Interest Rates</h3>
              <p className="text-gray-600">
                Good credit means you’re less risky to lenders, so they offer lower
                interest rates—saving you money in the long run.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Higher Credit Limits</h3>
              <p className="text-gray-600">
                With a strong credit history, lenders are more likely to offer higher
                credit limits, giving you more flexibility.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">More Favorable Loan Terms</h3>
              <p className="text-gray-600">
                You may receive loans with better terms, including lower fees or longer
                repayment periods.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Easier Rental Approvals</h3>
              <p className="text-gray-600">
                Landlords often check credit scores. A good score can make renting an
                apartment or home easier.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Lower Insurance Premiums</h3>
              <p className="text-gray-600">
                Some insurers use credit-based scores to set premiums. A good score can
                lead to lower insurance costs.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Improved Job Prospects</h3>
              <p className="text-gray-600">
                Some employers check credit reports for roles involving financial
                responsibility. A clean record helps.
              </p>
            </li>
            <li className="border-l-2 border-[#0283BB] pl-4">
              <h3 className="font-semibold text-lg text-gray-800">Stronger Bargaining Power</h3>
              <p className="text-gray-600">
                Good credit gives you leverage to negotiate better rates and rewards
                with lenders and service providers.
              </p>
            </li>
          </ul>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-4 text-[#0283BB]">
            What Affects Your Credit Score?
          </h2>
          <p className="text-gray-600 mb-6">
            Several key factors influence your credit score. Understanding these can help
            you build and maintain a strong credit profile:
          </p>

          <div className="space-y-2">
            <div>
              <h3 className="font-semibold text-lg text-gray-800">1. Payment History</h3>
              <p className="text-gray-600">
                Your history of on-time payments is the most significant factor. Late or missed
                payments can negatively impact your score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">2. Credit Utilization</h3>
              <p className="text-gray-600">
                This refers to the percentage of your available credit you’re using.
                Keeping it below 30% is ideal for a healthy score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">3. Length of Credit History</h3>
              <p className="text-gray-600">
                The longer your credit accounts have been open, the better. It shows lenders
                you have experience managing credit.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">4. Credit Mix</h3>
              <p className="text-gray-600">
                Having a variety of credit types—such as credit cards, personal loans,
                and mortgages—can positively influence your score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">5. New Credit Inquiries</h3>
              <p className="text-gray-600">
                Applying for new credit can result in hard inquiries. Too many in a short
                time may lower your score temporarily.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-4 text-[#0283BB]">How to Improve Your Credit Score</h2>
          <p className="text-gray-600 mb-6">
            Improving your credit score takes time and discipline. Here are some effective ways to boost it:
          </p>

          <div className="space-y-2">
            <div>
              <h3 className="font-semibold text-lg text-gray-800">1. Pay Bills on Time</h3>
              <p className="text-gray-600">
                Timely payments are the most important factor. Use reminders or auto-pay to avoid missing due dates.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">2. Keep Credit Utilization Low</h3>
              <p className="text-gray-600">
                Try to use less than 30% of your credit limit. Low usage signals responsible credit management.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">3. Don’t Close Old Accounts</h3>
              <p className="text-gray-600">
                Keeping older accounts open helps improve your average credit age and score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">4. Limit New Credit Applications</h3>
              <p className="text-gray-600">
                Too many applications can cause multiple hard inquiries. Apply only when necessary.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">5. Check Your Credit Reports</h3>
              <p className="text-gray-600">
                Regularly reviewing your credit reports helps you catch and fix errors that might hurt your score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">6. Diversify Your Credit Mix</h3>
              <p className="text-gray-600">
                A healthy mix of credit cards, loans, and other credit types can have a positive effect if managed well.
              </p>
            </div>
          </div>
        </div>



        <div>
          <h2 className="text-3xl font-bold mb-4 text-[#0283BB]">How Credit Scores Are Calculated</h2>
          <table className="w-full border border-gray-300 text-left">
            <thead className="bg-blue-100">
              <tr>
                <th className="p-2 border">Factor</th>
                <th className="p-2 border">Weightage</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="p-2 border">Payment History</td><td className="p-2 border">35%</td></tr>
              <tr><td className="p-2 border">Credit Utilization</td><td className="p-2 border">30%</td></tr>
              <tr><td className="p-2 border">Credit Age</td><td className="p-2 border">15%</td></tr>
              <tr><td className="p-2 border">Credit Mix</td><td className="p-2 border">10%</td></tr>
              <tr><td className="p-2 border">New Inquiries</td><td className="p-2 border">10%</td></tr>
            </tbody>
          </table>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-6 text-[#0283BB]">
            Comparison: Credit Score, Credit Rating, and Credit Report
          </h2>
          <div className="overflow-x-auto">
            <table className="min-w-full border border-gray-300 rounded-lg">
              <thead>
                <tr className="bg-blue-100 text-left">
                  <th className="p-4 border-b border-gray-300 w-1/4">Term</th>
                  <th className="p-4 border-b border-gray-300 w-3/4">Description</th>
                </tr>
              </thead>
              <tbody>
                <tr className="odd:bg-white even:bg-gray-50">
                  <td className="p-4 border-b border-gray-300 font-semibold">Credit Score</td>
                  <td className="p-4 border-b border-gray-300 text-gray-700">
                    A numeric value (usually 300-850) summarizing your creditworthiness, calculated using information from your credit report.
                  </td>
                </tr>
                <tr className="odd:bg-white even:bg-gray-50">
                  <td className="p-4 border-b border-gray-300 font-semibold">Credit Rating</td>
                  <td className="p-4 border-b border-gray-300 text-gray-700">
                    An evaluation often used for businesses or governments, reflecting their creditworthiness, usually expressed in letter grades (e.g., AAA, BBB).
                  </td>
                </tr>
                <tr className="odd:bg-white even:bg-gray-50">
                  <td className="p-4 border-b border-gray-300 font-semibold">Credit Report</td>
                  <td className="p-4 border-b border-gray-300 text-gray-700">
                    A detailed record of an individual’s or entity’s credit history, including accounts, payment behavior, inquiries, and public records.
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-6 text-[#0283BB]">
            Myths About Credit Scores
          </h2>

          <div className="space-y-6">
            <div>
              <h3 className="font-semibold text-lg text-gray-800">Myth 1: Checking Your Credit Score Hurts It</h3>
              <p className="text-gray-600">
                Checking your own credit score is a soft inquiry and does not affect your credit score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">Myth 2: Closing Credit Cards Improves Your Score</h3>
              <p className="text-gray-600">
                Closing old credit cards can actually lower your credit score by reducing your available credit and shortening your credit history.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">Myth 3: You Only Have One Credit Score</h3>
              <p className="text-gray-600">
                There are multiple credit scoring models and bureaus, so your credit score can vary depending on which one is used.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">Myth 4: Paying Off a Debt Removes It from Your Report</h3>
              <p className="text-gray-600">
                Paid debts can still appear on your credit report for up to seven years, but they are marked as paid and won’t negatively affect your score.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">Myth 5: Income Affects Your Credit Score</h3>
              <p className="text-gray-600">
                Your income is not factored into your credit score calculation.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-6 text-[#0283BB]">Credit Score Requirements for Loans</h2>
          <p className="text-gray-600 mb-6">
            Different types of loans have varying credit score requirements. Generally, a higher credit score improves your chances of loan approval and helps secure better interest rates.
          </p>
          <table className="w-full border border-gray-300 text-left">
            <thead className="bg-blue-100">
              <tr>
                <th className="p-2 border">Loan Type</th>
                <th className="p-2 border">Recommended Score</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="p-2 border">Personal Loan</td><td className="p-2 border">700+</td></tr>
              <tr><td className="p-2 border">Home Loan</td><td className="p-2 border">750+</td></tr>
              <tr><td className="p-2 border">Car Loan</td><td className="p-2 border">700+</td></tr>
              <tr><td className="p-2 border">Business Loan</td><td className="p-2 border">650+</td></tr>
              <tr><td className="p-2 border">Credit Card</td><td className="p-2 border">700+</td></tr>
            </tbody>
          </table>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-6 text-[#0283BB]">
            How to Dispute Credit Report Errors
          </h2>

          <div className="space-y-6">
            <div>
              <h3 className="font-semibold text-lg text-gray-800">1. Obtain Your Credit Report</h3>
              <p className="text-gray-600">
                Request a free copy of your credit report from each of the three major credit bureaus (Equifax, Experian, and TransUnion) at AnnualCreditReport.com.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">2. Review Your Report Carefully</h3>
              <p className="text-gray-600">
                Look for inaccuracies such as wrong personal information, accounts that don’t belong to you, incorrect balances, or outdated information.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">3. Gather Supporting Documentation</h3>
              <p className="text-gray-600">
                Collect any documents that support your dispute, such as payment records, correspondence, or identity proof.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">4. File a Dispute with the Credit Bureau</h3>
              <p className="text-gray-600">
                Submit your dispute online, by mail, or by phone. Clearly explain the error and include copies of your supporting documents.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg text-gray-800">5. Follow Up and Monitor Results</h3>
              <p className="text-gray-600">
                The credit bureau usually investigates within 30 days and notifies you of the results. Check your credit report again to confirm corrections.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-3xl font-bold mb-6 text-[#0283BB]">
            Trusted Credit Information Companies in India
          </h2>

          <div className="space-y-6 text-gray-700">
            <div>
              <h3 className="font-semibold text-lg">1. TransUnion CIBIL</h3>
              <p>
                One of the oldest and most widely used credit bureaus in India, providing credit scores and detailed reports for individuals and businesses.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg">2. Experian India</h3>
              <p>
                Offers credit information and analytics services with comprehensive credit reports and scores for consumers and lenders.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg">3. Equifax Credit Information Services Pvt. Ltd.</h3>
              <p>
                Provides credit reporting and risk assessment solutions for individuals and businesses across India.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-lg">4. CRIF High Mark Credit Information Services Pvt. Ltd.</h3>
              <p>
                A leading credit bureau offering credit scores, reports, and analytics to help lenders make informed decisions.
              </p>
            </div>
          </div>
        </div>

        <div className="py-10">
          <h1 className="text-4xl font-bold text-[#0282ba] mb-8">FAQ</h1>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={faq.question} className="border rounded-lg">
                <button
                  className="w-full flex justify-between items-center px-4 py-6 text-left font-medium text-gray-800 bg-gray-100 hover:bg-gray-200 transition"
                  onClick={() => toggleAnswer(index)}
                >
                  {faq.question}
                  <span className="text-xl">{activeIndex === index ? '-' : '+'}</span>
                </button>
                {activeIndex === index && (
                  <div className="px-4 py-3 text-gray-700 bg-white border-l-4 border-[#0282ba]">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

    </div >
  )
}

export default CreditScore;